-- Supabase-backed schema for GoDomain
-- Identity is owned by Supabase Auth (`auth.users`). Application data lives in public tables.

CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT UNIQUE,
  display_name TEXT NOT NULL DEFAULT 'Learner',
  index_number TEXT,
  phone_number TEXT,
  county TEXT,
  driving_school TEXT,
  driving_class TEXT,
  age TEXT,
  track TEXT,
  next_session TEXT DEFAULT 'Reverse parking drill',
  progress INTEGER NOT NULL DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
  lessons_complete TEXT NOT NULL DEFAULT '0 / 0',
  road_hours TEXT NOT NULL DEFAULT '0 hours',
  attendance TEXT NOT NULL DEFAULT '0%',
  coins INTEGER NOT NULL DEFAULT 0 CHECK (coins >= 0),
  coin_capacity INTEGER NOT NULL DEFAULT 100 CHECK (coin_capacity > 0),
  hp INTEGER NOT NULL DEFAULT 100 CHECK (hp >= 0),
  hp_capacity INTEGER NOT NULL DEFAULT 100 CHECK (hp_capacity > 0),
  energy INTEGER NOT NULL DEFAULT 100 CHECK (energy >= 0),
  energy_capacity INTEGER NOT NULL DEFAULT 100 CHECK (energy_capacity > 0),
  level TEXT NOT NULL DEFAULT 'Level 01',
  mentor TEXT DEFAULT 'Instructor',
  quiz_accuracy TEXT DEFAULT '0%',
  live_hours TEXT DEFAULT '0h',
  focus_rate TEXT DEFAULT '0%',
  badges_count INTEGER NOT NULL DEFAULT 0 CHECK (badges_count >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS learning_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  lesson_id TEXT NOT NULL,
  completed_step_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  progress_percent INTEGER NOT NULL DEFAULT 0 CHECK (progress_percent >= 0 AND progress_percent <= 100),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, lesson_id)
);

CREATE TABLE IF NOT EXISTS activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  detail TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ------------------------------
-- Lesson/Unit/Step content tables
-- ------------------------------

CREATE TABLE IF NOT EXISTS learning_units (
  unit_id TEXT PRIMARY KEY,
  unit_number INTEGER,
  label TEXT NOT NULL,
  title TEXT NOT NULL,
  summary TEXT,
  unlocked BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS lessons (
  lesson_id TEXT PRIMARY KEY,
  unit_id TEXT NOT NULL REFERENCES learning_units(unit_id) ON DELETE CASCADE,
  unit_number INTEGER,
  unit_label TEXT,
  lesson_number INTEGER,
  label TEXT NOT NULL,
  title TEXT NOT NULL,
  subtitle TEXT,
  icon TEXT,
  is_locked BOOLEAN NOT NULL DEFAULT FALSE,
  overview_title TEXT,
  overview_summary TEXT
);

CREATE TABLE IF NOT EXISTS lesson_steps (
  lesson_id TEXT NOT NULL REFERENCES lessons(lesson_id) ON DELETE CASCADE,
  step_id TEXT PRIMARY KEY,
  step_number INTEGER NOT NULL,
  kind TEXT,
  title TEXT NOT NULL,
  duration TEXT,
  detail TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS lesson_overview_topics (
  step_id TEXT NOT NULL REFERENCES lesson_steps(step_id) ON DELETE CASCADE,
  step_number INTEGER NOT NULL,
  topic_title TEXT,
  topic_points TEXT[] NOT NULL DEFAULT '{}',
  PRIMARY KEY (step_id)
);

CREATE INDEX IF NOT EXISTS profiles_email_idx ON profiles (email);
CREATE INDEX IF NOT EXISTS learning_progress_user_id_idx ON learning_progress (user_id);
CREATE INDEX IF NOT EXISTS learning_progress_user_updated_idx ON learning_progress (user_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS activities_user_id_idx ON activities (user_id);
CREATE INDEX IF NOT EXISTS activities_user_created_idx ON activities (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS lessons_unit_id_idx ON lessons (unit_id);
CREATE INDEX IF NOT EXISTS lesson_steps_lesson_id_idx ON lesson_steps (lesson_id);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS profiles_set_updated_at ON profiles;
CREATE TRIGGER profiles_set_updated_at
BEFORE UPDATE ON profiles
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, display_name)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NULLIF(NEW.raw_user_meta_data ->> 'display_name', ''), split_part(NEW.email, '@', 1), 'Learner')
  )
  ON CONFLICT (id) DO UPDATE
  SET email = EXCLUDED.email,
      display_name = COALESCE(public.profiles.display_name, EXCLUDED.display_name);

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW
EXECUTE FUNCTION public.handle_new_auth_user();

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_units ENABLE ROW LEVEL SECURITY;
ALTER TABLE lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE lesson_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE lesson_overview_topics ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS profiles_select_own ON profiles;
CREATE POLICY profiles_select_own ON profiles
FOR SELECT TO authenticated
USING ((SELECT auth.uid()) = id);

DROP POLICY IF EXISTS profiles_insert_own ON profiles;
CREATE POLICY profiles_insert_own ON profiles
FOR INSERT TO authenticated
WITH CHECK ((SELECT auth.uid()) = id);

DROP POLICY IF EXISTS profiles_update_own ON profiles;
CREATE POLICY profiles_update_own ON profiles
FOR UPDATE TO authenticated
USING ((SELECT auth.uid()) = id)
WITH CHECK ((SELECT auth.uid()) = id);

DROP POLICY IF EXISTS learning_progress_select_own ON learning_progress;
CREATE POLICY learning_progress_select_own ON learning_progress
FOR SELECT TO authenticated
USING ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS learning_progress_insert_own ON learning_progress;
CREATE POLICY learning_progress_insert_own ON learning_progress
FOR INSERT TO authenticated
WITH CHECK ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS learning_progress_update_own ON learning_progress;
CREATE POLICY learning_progress_update_own ON learning_progress
FOR UPDATE TO authenticated
USING ((SELECT auth.uid()) = user_id)
WITH CHECK ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS activities_select_own ON activities;
CREATE POLICY activities_select_own ON activities
FOR SELECT TO authenticated
USING ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS activities_insert_own ON activities;
CREATE POLICY activities_insert_own ON activities
FOR INSERT TO authenticated
WITH CHECK ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS learning_units_read_all ON learning_units;
CREATE POLICY learning_units_read_all ON learning_units
FOR SELECT TO anon, authenticated
USING (true);

DROP POLICY IF EXISTS lessons_read_all ON lessons;
CREATE POLICY lessons_read_all ON lessons
FOR SELECT TO anon, authenticated
USING (true);

DROP POLICY IF EXISTS lesson_steps_read_all ON lesson_steps;
CREATE POLICY lesson_steps_read_all ON lesson_steps
FOR SELECT TO anon, authenticated
USING (true);

DROP POLICY IF EXISTS lesson_overview_topics_read_all ON lesson_overview_topics;
CREATE POLICY lesson_overview_topics_read_all ON lesson_overview_topics
FOR SELECT TO anon, authenticated
USING (true);