-- Initial schema migrated through the Supabase CLI.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  display_name text not null default 'Learner',
  index_number text,
  phone_number text,
  county text,
  driving_school text,
  driving_class text,
  age text,
  track text,
  next_session text default 'Reverse parking drill',
  progress integer not null default 0 check (progress >= 0 and progress <= 100),
  lessons_complete text not null default '0 / 0',
  road_hours text not null default '0 hours',
  attendance text not null default '0%',
  coins integer not null default 0 check (coins >= 0),
  coin_capacity integer not null default 100 check (coin_capacity > 0),
  hp integer not null default 100 check (hp >= 0),
  hp_capacity integer not null default 100 check (hp_capacity > 0),
  energy integer not null default 100 check (energy >= 0),
  energy_capacity integer not null default 100 check (energy_capacity > 0),
  level text not null default 'Level 01',
  mentor text default 'Instructor',
  quiz_accuracy text default '0%',
  live_hours text default '0h',
  focus_rate text default '0%',
  badges_count integer not null default 0 check (badges_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.learning_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lesson_id text not null,
  completed_step_ids jsonb not null default '[]'::jsonb,
  progress_percent integer not null default 0 check (progress_percent >= 0 and progress_percent <= 100),
  updated_at timestamptz not null default now(),
  unique (user_id, lesson_id)
);

create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null,
  title text not null,
  detail text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.learning_units (
  unit_id text primary key,
  unit_number integer,
  label text not null,
  title text not null,
  summary text,
  unlocked boolean not null default true
);

create table if not exists public.lessons (
  lesson_id text primary key,
  unit_id text not null references public.learning_units(unit_id) on delete cascade,
  unit_number integer,
  unit_label text,
  lesson_number integer,
  label text not null,
  title text not null,
  subtitle text,
  icon text,
  is_locked boolean not null default false,
  overview_title text,
  overview_summary text
);

create table if not exists public.lesson_steps (
  lesson_id text not null references public.lessons(lesson_id) on delete cascade,
  step_id text primary key,
  step_number integer not null,
  kind text,
  title text not null,
  duration text,
  detail text not null
);

create table if not exists public.lesson_overview_topics (
  step_id text not null references public.lesson_steps(step_id) on delete cascade,
  step_number integer not null,
  topic_title text,
  topic_points text[] not null default '{}',
  primary key (step_id)
);

create index if not exists profiles_email_idx on public.profiles (email);
create index if not exists learning_progress_user_id_idx on public.learning_progress (user_id);
create index if not exists learning_progress_user_updated_idx on public.learning_progress (user_id, updated_at desc);
create index if not exists activities_user_id_idx on public.activities (user_id);
create index if not exists activities_user_created_idx on public.activities (user_id, created_at desc);
create index if not exists lessons_unit_id_idx on public.lessons (unit_id);
create index if not exists lesson_steps_lesson_id_idx on public.lesson_steps (lesson_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (
    new.id,
    new.email,
    coalesce(nullif(new.raw_user_meta_data ->> 'display_name', ''), split_part(new.email, '@', 1), 'Learner')
  )
  on conflict (id) do update
  set email = excluded.email,
      display_name = coalesce(public.profiles.display_name, excluded.display_name);

  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_auth_user();

alter table public.profiles enable row level security;
alter table public.learning_progress enable row level security;
alter table public.activities enable row level security;
alter table public.learning_units enable row level security;
alter table public.lessons enable row level security;
alter table public.lesson_steps enable row level security;
alter table public.lesson_overview_topics enable row level security;

create policy profiles_select_own on public.profiles
for select to authenticated
using ((select auth.uid()) = id);

create policy profiles_insert_own on public.profiles
for insert to authenticated
with check ((select auth.uid()) = id);

create policy profiles_update_own on public.profiles
for update to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create policy learning_progress_select_own on public.learning_progress
for select to authenticated
using ((select auth.uid()) = user_id);

create policy learning_progress_insert_own on public.learning_progress
for insert to authenticated
with check ((select auth.uid()) = user_id);

create policy learning_progress_update_own on public.learning_progress
for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy activities_select_own on public.activities
for select to authenticated
using ((select auth.uid()) = user_id);

create policy activities_insert_own on public.activities
for insert to authenticated
with check ((select auth.uid()) = user_id);

create policy learning_units_read_all on public.learning_units
for select to anon, authenticated
using (true);

create policy lessons_read_all on public.lessons
for select to anon, authenticated
using (true);

create policy lesson_steps_read_all on public.lesson_steps
for select to anon, authenticated
using (true);

create policy lesson_overview_topics_read_all on public.lesson_overview_topics
for select to anon, authenticated
using (true);
